# ~/.config/starship.toml

# Disable the blank line at the start of the prompt
add_newline = false

format = """
[‚ï≠‚îÄ](white)\
$username\
[@](turquoise)\
$hostname\
[-](white)\
$directory\
$git_branch\
$git_status\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$container\
$line_break\
[‚ï∞‚îÄ](white)\
$sudo\
$character\
"""

right_format="""
$cmd_duration\
$status\
$time\
"""

command_timeout = 1000

palette = "main"

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character] # The name of the module we are configuring is "character"
success_symbol = "[Œª](bold green)" # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
error_symbol = "[‚úò](bold red)"

[cmd_duration]
format = '\[[‚è± $duration]($style)\]'

[directory]
style = "fg:limegreen"
format = '\[[$path]($style)\]'
truncation_length = 3
truncation_symbol = "‚Ä¶/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "Ôúò "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ÔúòÔÑ™ "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important Ôúò " = " ÔúòÔÑ™ "

[git_branch]
format = '-\[[$symbol$branch]($style)'

[git_status]
stashed = '\$'
ahead = '‚á°${count}'
behind = '‚á£${count}'
diverged = '‚áï‚á°${ahead_count}‚á£${behind_count}'
conflicted = '='
deleted = '‚úò'
renamed = '¬ª'
modified = '!'
staged = '+'
untracked = '?'
format = '([ $all_status$ahead_behind]($style))\]'

[hostname]
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "fg:orange"
format = '[$hostname]($style)\)'

[palettes.main]
hotpink = "#DF005F"
orange = "#DF5F00"
turquoise = "#5FDFFF"
limegreen = "#87FF00"

[status]
format = '[\[$symbol$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
disabled = false
format = '[$symbol]($style)'

[time]
disabled = false
use_12hr = true
utc_time_offset = "6"
#time_format = "%r" # Hour:Minute Format
style = "fg:#33658A"
format = '[ ‚ô• $time ]($style)'

[username]
show_always = true
style_user = "fg:hotpink"
style_root = "fg:red"
format = '\([$user]($style)'


# Symbols
[aws]
format = '-\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '-\[[$symbol($version)]($style)\]'

[c]
format = '-\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '-\[[$symbol($version)]($style)\]'

[cobol]
format = '-\[[$symbol($version)]($style)\]'

[conda]
format = '-\[[$symbol$environment]($style)\]'

[crystal]
format = '-\[[$symbol($version)]($style)\]'

[daml]
format = '-\[[$symbol($version)]($style)\]'

[dart]
format = '-\[[$symbol($version)]($style)\]'

[deno]
format = '-\[[$symbol($version)]($style)\]'

[docker_context]
format = '-\[[$symbol$context]($style)\]'

[dotnet]
format = '-\[[$symbol($version)(üéØ $tfm)]($style)\]'

[elixir]
format = '-\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '-\[[$symbol($version)]($style)\]'

[erlang]
format = '-\[[$symbol($version)]($style)\]'

[gcloud]
format = '-\[[$symbol$account(@$domain)(\($region\))]($style)\]'

#[git_branch]
#format = '\[[$symbol$branch]($style)\]'

#[git_status]
#format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '-\[[$symbol($version)]($style)\]'

[haskell]
format = '-\[[$symbol($version)]($style)\]'

[helm]
format = '-\[[$symbol($version)]($style)\]'

[hg_branch]
format = '-\[[$symbol$branch]($style)\]'

[java]
format = '-\[[$symbol($version)]($style)\]'

[julia]
format = '-\[[$symbol($version)]($style)\]'

[kotlin]
format = '-\[[$symbol($version)]($style)\]'

[kubernetes]
format = '-\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '-\[[$symbol($version)]($style)\]'

[memory_usage]
format = '-\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '-\[[$symbol$project]($style)\]'

[nim]
format = '-\[[$symbol($version)]($style)\]'

[nix_shell]
format = '-\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '-\[[$symbol($version)]($style)\]'

[ocaml]
format = '-\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[openstack]
format = '-\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '-\[[$symbol$version]($style)\]'

[perl]
format = '-\[[$symbol($version)]($style)\]'

[php]
format = '-\[[$symbol($version)]($style)\]'

[pulumi]
format = '-\[[$symbol$stack]($style)\]'

[purescript]
format = '-\[[$symbol($version)]($style)\]'

[python]
format = '-\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '-\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '-\[[$symbol($version)]($style)\]'

[ruby]
format = '-\[[$symbol($version)]($style)\]'

[rust]
format = '-\[[$symbol($version)]($style)\]'

[scala]
format = '-\[[$symbol($version)]($style)\]'

[spack]
format = '-\[[$symbol$environment]($style)\]'

#[sudo]
#format = '\[[as $symbol]\]'

[swift]
format = '-\[[$symbol($version)]($style)\]'

[terraform]
format = '-\[[$symbol$workspace]($style)\]'

#[time]
#format = '\[[$time]($style)\]'

#[username]
#format = '\[[$user]($style)\]'

[vagrant]
format = '-\[[$symbol($version)]($style)\]'

[vlang]
format = '-\[[$symbol($version)]($style)\]'

[zig]
format = '-\[[$symbol($version)]($style)\]'
